<a href="https://colab.research.google.com/github/Aasrith22/external/blob/main/activation_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
def n(data):
    m = np.mean(data, axis=0)
    s = np.std(data, axis=0)
    return (data - m) / s
def s(x):
    return 1 / (1 + np.exp(-x))
def r(x):
    return np.maximum(0, x)
def t(x):
    return np.tanh(x)
d = np.array([
    [2, 4, 5],
    [5, 6, 3],
    [7, 2, 8],
    [1, 9, 2]
])
nd = n(d)
so = s(nd)
ro = r(nd)
to = t(nd)
print("Input data:")
print(d)
print("\nNormalized data:")
print(nd)
print("\nSigmoid activation output:")
print(so)
print("\nReLU activation output:")
print(ro)
print("\nTanh activation output:")
print(to)


Input data:
[[2 4 5]
 [5 6 3]
 [7 2 8]
 [1 9 2]]

Normalized data:
[[-0.73379939 -0.48336824  0.21821789]
 [ 0.52414242  0.29002095 -0.65465367]
 [ 1.36277029 -1.25675744  1.52752523]
 [-1.15311332  1.45010473 -1.09108945]]

Sigmoid activation output:
[[0.32436153 0.38145708 0.55433901]
 [0.62811589 0.57200126 0.34194161]
 [0.79620957 0.22153259 0.82164394]
 [0.23992088 0.81001455 0.25141318]]

ReLU activation output:
[[0.         0.         0.21821789]
 [0.52414242 0.29002095 0.        ]
 [1.36277029 0.         1.52752523]
 [0.         1.45010473 0.        ]]

Tanh activation output:
[[-0.62538427 -0.44893707  0.21481884]
 [ 0.48089081  0.28215409 -0.57479445]
 [ 0.87703404 -0.8501677   0.91000014]
 [-0.81878283  0.89571358 -0.79727543]]
